export const locationOptions = [
  "Riyadh",
  "Jeddah",
  "Mecca",
  "Medina",
  "Dammam",
  "Khobar",
  "Dhahran",
  "Taif",
  "Abha",
  "Khamis Mushait",
  "Al Hofuf",
  "Al Mubarraz",
  "Jubail",
  "Hafar Al-Batin",
  "Al Qatif",
  "Najran",
  "Yanbu",
  "Al Khafji",
  "Buraidah",
  "Unaizah",
  "Hail",
  "Arar",
  "Sakaka",
  "Jizan",
  "Tabuk",
  "Al Bahah",
  "Al Wajh",
  "Ras Tanura",
  "Al Majma'ah",
  "Al Qurayyat",
  "Al Lith",
  "Al Aflaj",
  "Al Kharj",
  "Rabigh",
  "Turaif",
  "Al Ula",
  "Al Birk",
  "Al Duwadimi",
  "Thuwal",
  "Duba",
  "Wadi ad-Dawasir",
  "Baljurashi",
  "Al Muzahimiyah",
  "Al Namas",
  "Bisha",
  "Mahd adh Dhahab",
  "Umluj",
  "Al Bukayriyah",
  "Samtah",
  "Sabya",
  "Ranyah",
  "Qurayyat",
  "Sharurah",
  "Ad Dilam",
  "Muzahmiyya",
  "Afif",
  "Al Zulfi",
  "Al Artawiyah",
  "Hotat Bani Tamim",
  "Dawadmi",
  "Al-'Uyayna",
  "Qatif",
  "Al Jumum",
  "Al Awjam",
  "Al Darb",
  "Tanumah",
  "Turubah"
];

export const roleOptions = [
  {
    category: "Project Management & Controls",
    positions: [
      "Project Director",
      "Project Manager",
      "Deputy Project Manager",
      "Project Control Manager",
      "Planning Supervisor",
      "Planning Engineers",
      "Schedulers",
      "Cost Control Engineer",
      "Risk Manager",
      "Contract Administrator",
      "Interface Manager",
      "Document Controller"
    ]
  },
   {
    category: "Information Technology (IT)",
    positions: [
      "Software Developer",
      "Frontend Developer",
      "Backend Developer",
      "Full Stack Developer",
      "Mobile App Developer (iOS/Android)",
      "DevOps Engineer",
      "Cloud Engineer",
      "Data Scientist",
      "Data Analyst",
      "Machine Learning Engineer",
      "AI Engineer",
      "Cybersecurity Analyst",
      "Network Administrator",
      "System Administrator",
      "Database Administrator (DBA)",
      "IT Support Specialist",
      "QA/Test Engineer",
      "Automation Tester",
      "Scrum Master",
      "Product Manager",
      "Business Analyst",
      "UI/UX Designer",
      "Technical Writer",
      "IT Project Manager"
    ]
  },
  {
    category: "Engineering",
    positions: [
      // Civil/Structural
      "Civil Engineer",
      "Structural Engineer",
      "Geotechnical Engineer",
      "Draftsman",

      // Mechanical
      "Mechanical Engineer",
      "HVAC Engineer",
      "Equipment Engineer",
      "Stress Analyst",

      // Piping
      "Piping Engineer",
      "Layout Engineer",
      "Piping Material Engineer",
      "3D Modeler/Draftsman",

      // Electrical
      "Electrical Engineer",
      "Power Systems Engineer",
      "Lighting & Earthing Designer",

      // Instrumentation & Automation
      "Instrumentation Engineer",
      "Control Systems Engineer (DCS/PLC)",
      "Analyzer Engineer",

      // Process
      "Process Engineer",
      "Simulation Specialist",
      "HAZOP/Process Safety Engineer",

      // MEP
      "MEP Engineer",

      // Project Engineering
      "Lead Discipline Engineers",
      "Design Coordinator",
      "Interface Engineer"
    ]
  },
  {
    category: "Procurement",
    positions: [
      "Procurement Manager",
      "Procurement Engineer",
      "Buyer",
      "Expeditor",
      "Logistics Coordinator",
      "Material Controller",
      "Vendor Coordinator"
    ]
  },
  {
    category: "Construction",
    positions: [
      "Construction Manager",
      "General Superintendent",
      "Site Civil Engineers",
      "Site Mechanical Engineers",
      "Site Electrical Engineers",
      "Site I&C Engineers",
      "MEP Supervisor",
      "MEP Foreman",
      "Construction Supervisors/Foremen (by discipline)",
      "Surveyor",
      "Site Admin/Timekeeper",
      "Skilled Labor Plumbers",
      "Skilled Labor Welders",
      "Skilled Labor Fitters",
      "Skilled Labor Electricians",
      "Skilled Labor  Riggers",
      "Skilled Labor Scaffolders"
            
      
    ]
  },
  {
    category: "Quality Assurance & Quality Control (QA/QC)",
    positions: [
      "QA/QC Manager",
      "Discipline Supervisors & Inspectors",
      "NDT Technician",
      "Calibration Engineer",
      "Procurement QA/QC Engineer"
    ]
  },
  {
    category: "HSE (Health, Safety, Environment)",
    positions: [
      "HSE Manager",
      "Safety Officer",
      "Safety Supervisor",
      "Environmental Engineer",
      "Industrial Hygienist"
    ]
  },
  {
    category: "Commissioning & Start-up",
    positions: [
      "Commissioning Manager",
      "Commissioning Engineers Process",
      "Commissioning Engineers Mechanical",
      "Commissioning Engineers Electrical",
      "Commissioning Engineers I&C",
      "Pre-Commissioning Technicians",
      "DCS/PLC Engineers",
      "Punch List Coordinator",
      "System Completion Coordinator"
    ]
  },
  {
    category: "General Services & Site Support",
    positions: [
      "Secretary / Administrative Assistant",
      "Male Nurse",
      "Resident Doctor",
      "Driver Light Vehicle",
      "Driver Bus",
      "Crane Operator",
      "Heavy Equipment Operator Excavator",
       "Heavy Equipment Operator Loader",
        "Heavy Equipment Operator Dozer",
      "Forklift Operator",
      "Manlift Operator",
      "Utility Worker / General Labor",
      "Camp Boss / Camp Administrator",
      "Janitor / Housekeeping Staff",
      "Cook / Catering Staff",
      "Security Guard"
    ]
  }
];

export const certificationOptions = [
  'AWS Certified', 'Azure Certified', 'Google Cloud Certified', 'Certified Scrum Master',
  'PMP Certified', 'Oracle Certified', 'Salesforce Certified', 'Adobe Certified',
  'Cisco Certified', 'Red Hat Certified',
    "PMP® – Project Management Professional",
  "PGMP® – Program Management Professional",
  "RMP® – Risk Management Professional",
  "Certified Engineer (PE / Licensed Engineer)",
  "Construction Management Certification (CMCI or CMAA)",
  "Primavera P6 / MS Project – Project Planning Certification",
  "ISO 9001 Lead Auditor",
  "Factory Acceptance Testing (FAT)",
  "Site Acceptance Testing (SAT)",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC QC Inspector",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Vendor QC Inspector",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Procurement QC",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Procurement QC Manager",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC QC Supervisor",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC QA / QC Manager",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Permit Receiver",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Safety Officer",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Safety Supervisor",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Safety Manager",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Scaffolding Supervisor Inspector",
  "Saudi Aramco / SABIC / MAADEN / RC / SEC Operator",
  "Saudi Aramco / SABIC / MAADEN / Technician",
  "Saudi Aramco / SABIC / MAADEN /  Welder ",
  "Saudi Aramco / SABIC / MAADEN / Mill Wright",
  "Saudi Aramco / SABIC / MAADEN / Scaffolder",
  "Saudi Aramco / SABIC / MAADEN / FRP Laminators",
  "AutoCAD / SolidWorks Certification",
  "HAZOP / SIL Studies",
  "Third-Party Inspectors",
  "Electrical, Instrumentation & Control System",
  "EEHA – Electrical Equipment in Hazardous Areas",
  "IECEx CoPC – Certified Competence in Explosive Atmospheres",
  "Control Systems Technician",
  "Certified Automation Professional",
  "API 554 – Process Control Systems",
  "Foundation Fieldbus / HART Training",
  "Loop Calibration & Instrument Commissioning Certification",
  "Vendor DCS/PLC Certifications  Honeywell",
  "Vendor DCS/PLC Certifications, Emerson ",
  "Vendor DCS/PLC Certifications, Yokogawa",
  "Vendor DCS/PLC Certifications,ABB",
  "SmartPlant Instrumentation (SPI / Intools)",
  "AutoCAD / Certification",
  "Certified Fiber Optic Technician",
  "Power Distribution (MV/LV)",
  "Transformers, Switchgear, Motors",
  "Earthing, Lighting, Lightning Protection",
  "OTDR Testing Certification, EXFO",
  "OTDR Testing Certification, Fluke",
  "OTDR Testing Certification, Viavi",
  "OT Cybersecurity Compliance, ISA",
  "OT Cybersecurity Compliance, IEC 62443",
  "CCTV, Access Control",
  " PA/GA",
  " Access Control",
  "Radio Systems",
  "Structured Cabling",
  "Pressure Vessel Inspector",
  "Piping Inspector",
  "Piping System Inspection",
  "Fitness-for-Service",
  "Storage Tank Inspector",
  "Welding Inspection & Metallurgy",
  "Pipeline Construction Inspector",
  "BGAS-CSWIP Grades Coating & Painting Inspector",
  "PCN Level NDT Certification",
  "ISO International NDT Qualification",
  "NACE / AMPP CIP Levels Coating Inspector",
  "WPS / PQR / WPQ Welding Procedure & Welder Qualifications",
  "Future Pipe Certified FRP / GRP / RTR Laminators",
  "Amiantit Pipe Certified FRP / GRP / RTR Laminators",
  "ASME Certification",
  "ASME B31.3 Certification Process Piping",
  "Hydrostatic/Pneumatic Pressure Testing Certification",
  "Valve Testing & Repair Certification",
  "Welding & Fabrication",
  "CSWIP 3.1 Welding Inspector",
  "CSWIP 3.2 Senior Welding Inspector",
  "AWS D1.1 / D1.6 Structural Welding",
  "WPS/PQR Approvals (Aramco, SABIC, Maaden, etc.)",
  "AWS CWI Certified Welding Inspector",
  "AWS SCWI Senior Certified Welding Inspector",
  "ASNT Level II / III NDT (RT, UT, MT, PT, VT)",
  "Welder Qualification Tests",
  "PWHT",
  "Hydrotesting",
  "Vibration Analysis Certification (ISO Category I–IV)",
  "Laser Shaft Alignment & Balancing Training",
  "Pump & Compressor Maintenance Certification",
  "Hardness Testing Certification",
  "Positive Material Identification (PMI) Training",
  "QC Documentation & Turnover Certification",
  "Flange Management & Bolt Torquing Certification",
  "AutoCAD / Civil 3D / Revit Certification",
  "SAP2000 / STAAD Pro Structural Design Certification",
  "QA/QC Civil Inspector Certification",
  "TWI CSWIP – Plant Inspector (for civil elements)",
  "Material Testing Certification Concrete",
   "Material Testing Certification Aggregate",
    "Material Testing Certification Asphalt)",
     "Material Testing Certification Soil",
  "Surveying Certification (Total Station, GPS)",
  "Surveying Certification (Total Station,GIS)",
  "ACI Certification – American Concrete Institute",
  "ACI Concrete Field Testing Technician – Grade I",
  "Structural Steel Erection ",
  "Inspection Certification",
  "Foundation / Pile Driving",
  " Testing Certification",
  "Formwork",
  " Shuttering Supervisor Training",
  "Soil Testing Certification",
  "SPT (Standard Penetration Test) Training",
  "Plate Load Test",
  "CBR Testing Certification",
  "Compaction Testing",
  " Field Density Certification",
  "Rock Quality Designation (RQD)",
  " Borehole Logging Certification",
  "Total Station Operation & Certification",
  "GPS / GNSS Surveying Certification",
  "GIS (Geographical Information Systems) Certification",
  "AutoCAD Civil 3D for Surveyors",
  "Road and Highway Design Certification",
  "NEBOSH / NEBOSH /IOSH HSE Certifications",
  "OSHA Construction Safety Certification",
  "Environmental Impact Assessment (EIA)",
  "Rigging & Lifting Supervisor/Inspector Certification",
  "Mechanical Isolation & LOTO Training",
  "Aramco Rigger Level I",
  "Aramco Rigger Level II",
  "Aramco Rigger Level III",
  "Rigger Level I",
  "Rigger Level II",
  "Rigger Level III",
  "Heavy Equipment Operator",
  "Wastewater, Air Emission Controls",
  "Noise & Vibration Mitigation"
];

export const educationOptions = [
  'High School',
   'Diploma',
   'Bachelor’s Degree',
    'Master’s Degree',
     'PhD',
     "MCA",
     "BCA",
     "BSC",
     "MSC",
  "Bachelor of Computer Engineering (B.E / B.Tech)",
    "Master of Computer Engineering (M.E / M.Tech)",
  "Bachelor of Electrical Engineering (B.E / B.Tech)",
  "Master of Electrical Engineering (M.E / M.Tech)",
  "Bachelor of Electronic Engineering (B.E / B.Tech)",
   "Master of Electronic Engineering (M.E / M.Tech)",
  "Bachelor of Instrumentation Engineering (B.E / B.Tech)",
   "Bachelor of Chemical Engineering (B.E / B.Tech)",
  "Master of Chemical Engineering (M.E / M.Tech)",
  "Master of Civil Engineering (M.E / M.Tech)",
  "Master of Mechanical Engineering (M.E / M.Tech)",
  "Master of Instrumentation Engineering (M.E / M.Tech)",
  "Diploma in Civil Engineering",
  "Diploma in Mechanical Engineering",
  "Diploma in Electrical Engineering",
  "Diploma in Instrumentation Engineering",
  "Diploma in Piping",
  "Diploma in Safety",
  "Bachelor of Science",
  "Master of Science",
  "Bachelor of Arts",
  "Master of Arts",
  "Bachelor of Commerce",
  "Master of Commerce",
  "BBA",
  "MBA",
  "B.Com",
  "M.Com",
  "BA",
  "MA",
  "ITI",
  "10 PASS",
  "12 PASS",
  "Other"
];

export const genderOptions = ["Male", "Female", "Other"];

export const nationalityOptions = [
  "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan",
  "Argentine", "Armenian", "Australian", "Austrian", "Azerbaijani",
  "Bahamian", "Bahraini", "Bangladeshi", "Barbadian", "Belarusian", "Belgian",
  "Belizean", "Beninese", "Bhutanese", "Bolivian", "Bosnian", "Brazilian",
  "British", "Bruneian", "Bulgarian", "Burkinabé", "Burmese", "Burundian",
  "Cambodian", "Cameroonian", "Canadian", "Cape Verdean", "Central African",
  "Chadian", "Chilean", "Chinese", "Colombian", "Comorian", "Congolese",
  "Costa Rican", "Croatian", "Cuban", "Cypriot", "Czech", "Danish", "Djiboutian",
  "Dominican", "Dutch", "East Timorese", "Ecuadorean", "Egyptian", "Emirati",
  "Equatorial Guinean", "Eritrean", "Estonian", "Ethiopian", "Fijian", "Finnish",
  "French", "Gabonese", "Gambian", "Georgian", "German", "Ghanaian", "Greek",
  "Grenadian", "Guatemalan", "Guinean", "Guyanese", "Haitian", "Honduran",
  "Hungarian", "Icelandic", "Indian", "Indonesian", "Iranian", "Iraqi",
  "Irish", "Israeli", "Italian", "Ivorian", "Jamaican", "Japanese", "Jordanian",
  "Kazakh", "Kenyan", "Kuwaiti", "Kyrgyz", "Lao", "Latvian", "Lebanese",
  "Liberian", "Libyan", "Lithuanian", "Luxembourgish", "Macedonian", "Malagasy",
  "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese", "Mauritanian",
  "Mauritian", "Mexican", "Moldovan", "Monégasque", "Mongolian", "Montenegrin",
  "Moroccan", "Mozambican", "Namibian", "Nepalese", "New Zealander", "Nicaraguan",
  "Nigerien", "Nigerian", "North Korean", "Norwegian", "Omani", "Pakistani",
  "Palestinian", "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian",
  "Philippine", "Polish", "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan",
  "Salvadoran", "Samoan", "Saudi", "Scottish", "Senegalese", "Serbian", "Seychellois",
  "Sierra Leonean", "Singaporean", "Slovak", "Slovenian", "Somali", "South African",
  "South Korean", "Spanish", "Sri Lankan", "Sudanese", "Surinamese", "Swazi",
  "Swedish", "Swiss", "Syrian", "Taiwanese", "Tajik", "Tanzanian", "Thai",
  "Togolese", "Tongan", "Trinidadian", "Tunisian", "Turkish", "Turkmen", "Tuvaluan",
  "Ugandan", "Ukrainian", "Uruguayan", "Uzbek", "Venezuelan", "Vietnamese",
  "Welsh", "Yemeni", "Zambian", "Zimbabwean"
];

export const maritalStatusOptions = [
  "Single",
  "Married",
  "Divorced",
  "Widowed",
  "Separated",
  "Registered Partnership"
];

export const CountryOptions = [
  "India",
  "Saudi Arabia",  // Use space instead of underscore for consistency
  "Other"
];


export const CityOptions = [
 "Riyadh",
  "Jeddah",
  "Mecca",
  "Medina",
  "Dammam",
  "Khobar",
  "Dhahran",
  "Taif",
  "Abha",
  "Khamis Mushait",
  "Al Hofuf",
  "Al Mubarraz",
  "Jubail",
  "Hafar Al-Batin",
  "Al Qatif",
  "Najran",
  "Yanbu",
  "Al Khafji",
  "Buraidah",
  "Unaizah",
  "Hail",
  "Arar",
  "Sakaka",
  "Jizan",
  "Tabuk",
  "Al Bahah",
  "Al Wajh",
  "Ras Tanura",
  "Al Majma'ah",
  "Al Qurayyat",
  "Al Lith",
  "Al Aflaj",
  "Al Kharj",
  "Rabigh",
  "Turaif",
  "Al Ula",
  "Al Birk",
  "Al Duwadimi",
  "Thuwal",
  "Duba",
  "Wadi ad-Dawasir",
  "Baljurashi",
  "Al Muzahimiyah",
  "Al Namas",
  "Bisha",
  "Mahd adh Dhahab",
  "Umluj",
  "Al Bukayriyah",
  "Samtah",
  "Sabya",
  "Ranyah",
  "Qurayyat",
  "Sharurah",
  "Ad Dilam",
  "Muzahmiyya",
  "Afif",
  "Al Zulfi",
  "Al Artawiyah",
  "Hotat Bani Tamim",
  "Dawadmi",
  "Al-'Uyayna",
  "Qatif",
  "Al Jumum",
  "Al Awjam",
  "Al Darb",
  "Tanumah",
  "Turubah",
   "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Surat",
  "Jaipur",
  "Lucknow",
  "Bhopal",
  "Indore",
  "Nagpur",
  "Kanpur",
  "Patna",
  "Coimbatore",
  "Kochi",
  "Thiruvananthapuram",
  "Chandigarh"
];

// constants/FormOptions.js

export const totalExperienceOptions = [
  "Fresher",
  ...Array.from({ length: 11 }, (_, i) => `${i + 1} month${i + 1 > 1 ? "s" : ""}`), // 1 to 11 months
  ...Array.from({ length: 20 }, (_, i) => `${i + 1} year${i + 1 > 1 ? "s" : ""}`), // 1 to 20 years
  "20+ years"
];

export const CountryCodes = [
  { name: "Afghanistan", code: "+93" },
  { name: "Albania", code: "+355" },
  { name: "Algeria", code: "+213" },
  { name: "Andorra", code: "+376" },
  { name: "Angola", code: "+244" },
  { name: "Argentina", code: "+54" },
  { name: "Armenia", code: "+374" },
  { name: "Aruba", code: "+297" },
  { name: "Australia", code: "+61" },
  { name: "Austria", code: "+43" },
  { name: "Azerbaijan", code: "+994" },
  { name: "Bahrain", code: "+973" },
  { name: "Bangladesh", code: "+880" },
  { name: "Belarus", code: "+375" },
  { name: "Belgium", code: "+32" },
  { name: "Belize", code: "+501" },
  { name: "Benin", code: "+229" },
  { name: "Bhutan", code: "+975" },
  { name: "Bolivia", code: "+591" },
  { name: "Bosnia and Herzegovina", code: "+387" },
  { name: "Botswana", code: "+267" },
  { name: "Brazil", code: "+55" },
  { name: "British Indian Ocean Territory", code: "+246" },
  { name: "Brunei", code: "+673" },
  { name: "Bulgaria", code: "+359" },
  { name: "Burkina Faso", code: "+226" },
  { name: "Burundi", code: "+257" },
  { name: "Cambodia", code: "+855" },
  { name: "Cameroon", code: "+237" },
  { name: "Cape Verde", code: "+238" },
  { name: "Central African Republic", code: "+236" },
  { name: "Chad", code: "+235" },
  { name: "Chile", code: "+56" },
  { name: "China", code: "+86" },
  { name: "Colombia", code: "+57" },
  { name: "Comoros", code: "+269" },
  { name: "Cook Islands", code: "+682" },
  { name: "Costa Rica", code: "+506" },
  { name: "Croatia", code: "+385" },
  { name: "Cuba", code: "+53" },
  { name: "Curaçao", code: "+599" },
  { name: "Cyprus", code: "+357" },
  { name: "Czech Republic", code: "+420" },
  { name: "Democratic Republic of the Congo", code: "+243" },
  { name: "Denmark", code: "+45" },
  { name: "Djibouti", code: "+253" },
  { name: "East Timor", code: "+670" },
  { name: "Ecuador", code: "+593" },
  { name: "Egypt", code: "+20" },
  { name: "El Salvador", code: "+503" },
  { name: "Equatorial Guinea", code: "+240" },
  { name: "Eritrea", code: "+291" },
  { name: "Estonia", code: "+372" },
  { name: "Ethiopia", code: "+251" },
  { name: "Falkland Islands", code: "+500" },
  { name: "Faroe Islands", code: "+298" },
  { name: "Fiji", code: "+679" },
  { name: "Finland", code: "+358" },
  { name: "France", code: "+33" },
  { name: "French Guiana", code: "+594" },
  { name: "French Polynesia", code: "+689" },
  { name: "Gabon", code: "+241" },
  { name: "Gambia", code: "+220" },
  { name: "Georgia", code: "+995" },
  { name: "Germany", code: "+49" },
  { name: "Ghana", code: "+233" },
  { name: "Gibraltar", code: "+350" },
  { name: "Greece", code: "+30" },
  { name: "Greenland", code: "+299" },
  { name: "Guadeloupe", code: "+590" },
  { name: "Guatemala", code: "+502" },
  { name: "Guernsey", code: "+44-1481" },
  { name: "Guinea", code: "+224" },
  { name: "Guinea-Bissau", code: "+245" },
  { name: "Guyana", code: "+592" },
  { name: "Haiti", code: "+509" },
  { name: "Honduras", code: "+504" },
  { name: "Hong Kong", code: "+852" },
  { name: "Hungary", code: "+36" },
  { name: "Iceland", code: "+354" },
  { name: "India", code: "+91" },
  { name: "Indonesia", code: "+62" },
  { name: "Iran", code: "+98" },
  { name: "Iraq", code: "+964" },
  { name: "Ireland", code: "+353" },
  { name: "Isle of Man", code: "+44-1624" },
  { name: "Israel", code: "+972" },
  { name: "Italy", code: "+39" },
  { name: "Ivory Coast", code: "+225" },
  { name: "Japan", code: "+81" },
  { name: "Jersey", code: "+44-1534" },
  { name: "Jordan", code: "+962" },
  { name: "Kenya", code: "+254" },
  { name: "Kiribati", code: "+686" },
  { name: "Kosovo", code: "+383" },
  { name: "Kuwait", code: "+965" },
  { name: "Kyrgyzstan", code: "+996" },
  { name: "Laos", code: "+856" },
  { name: "Latvia", code: "+371" },
  { name: "Lebanon", code: "+961" },
  { name: "Lesotho", code: "+266" },
  { name: "Liberia", code: "+231" },
  { name: "Libya", code: "+218" },
  { name: "Liechtenstein", code: "+423" },
  { name: "Lithuania", code: "+370" },
  { name: "Luxembourg", code: "+352" },
  { name: "Macao", code: "+853" },
  { name: "Madagascar", code: "+261" },
  { name: "Malawi", code: "+265" },
  { name: "Malaysia", code: "+60" },
  { name: "Maldives", code: "+960" },
  { name: "Mali", code: "+223" },
  { name: "Malta", code: "+356" },
  { name: "Marshall Islands", code: "+692" },
  { name: "Martinique", code: "+596" },
  { name: "Mauritania", code: "+222" },
  { name: "Mauritius", code: "+230" },
  { name: "Mexico", code: "+52" },
  { name: "Micronesia", code: "+691" },
  { name: "Moldova", code: "+373" },
  { name: "Monaco", code: "+377" },
  { name: "Mongolia", code: "+976" },
  { name: "Montenegro", code: "+382" },
  { name: "Morocco", code: "+212" },
  { name: "Mozambique", code: "+258" },
  { name: "Myanmar", code: "+95" },
  { name: "Namibia", code: "+264" },
  { name: "Nauru", code: "+674" },
  { name: "Nepal", code: "+977" },
  { name: "Netherlands", code: "+31" },
  { name: "New Caledonia", code: "+687" },
  { name: "New Zealand", code: "+64" },
  { name: "Nicaragua", code: "+505" },
  { name: "Niger", code: "+227" },
  { name: "Nigeria", code: "+234" },
  { name: "Niue", code: "+683" },
  { name: "North Korea", code: "+850" },
  { name: "North Macedonia", code: "+389" },
  { name: "Norway", code: "+47" },
  { name: "Oman", code: "+968" },
  { name: "Pakistan", code: "+92" },
  { name: "Palau", code: "+680" },
  { name: "Palestine", code: "+970" },
  { name: "Panama", code: "+507" },
  { name: "Papua New Guinea", code: "+677" },
  { name: "Paraguay", code: "+595" },
  { name: "Peru", code: "+51" },
  { name: "Philippines", code: "+63" },
  { name: "Poland", code: "+48" },
  { name: "Portugal", code: "+351" },
  { name: "Qatar", code: "+974" },
  { name: "Republic of the Congo", code: "+242" },
  { name: "Reunion", code: "+262" },
  { name: "Romania", code: "+40" },
  { name: "Russia", code: "+7" },
  { name: "Rwanda", code: "+250" },
  { name: "Saint Helena", code: "+290" },
  { name: "Saint Pierre and Miquelon", code: "+508" },
  { name: "Samoa", code: "+685" },
  { name: "San Marino", code: "+378" },
  { name: "Sao Tome and Principe", code: "+239" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "Senegal", code: "+221" },
  { name: "Serbia", code: "+381" },
  { name: "Seychelles", code: "+248" },
  { name: "Sierra Leone", code: "+232" },
  { name: "Singapore", code: "+65" },
  { name: "Slovakia", code: "+421" },
  { name: "Slovenia", code: "+386" },
  { name: "Somalia", code: "+252" },
  { name: "South Africa", code: "+27" },
  { name: "South Korea", code: "+82" },
  { name: "South Sudan", code: "+211" },
  { name: "Spain", code: "+34" },
  { name: "Sri Lanka", code: "+94" },
  { name: "Sudan", code: "+249" },
  { name: "Suriname", code: "+597" },
  { name: "Swaziland", code: "+268" },
  { name: "Sweden", code: "+46" },
  { name: "Switzerland", code: "+41" },
  { name: "Syria", code: "+963" },
  { name: "Taiwan", code: "+886" },
  { name: "Tajikistan", code: "+992" },
  { name: "Tanzania", code: "+255" },
  { name: "Thailand", code: "+66" },
  { name: "Togo", code: "+228" },
  { name: "Tokelau", code: "+690" },
  { name: "Tonga", code: "+676" },
  { name: "Tunisia", code: "+216" },
  { name: "Turkey", code: "+90" },
  { name: "Turkmenistan", code: "+993" },
  { name: "Tuvalu", code: "+688" },
  { name: "Uganda", code: "+256" },
  { name: "Ukraine", code: "+380" },
  { name: "United Arab Emirates", code: "+971" },
  { name: "United Kingdom", code: "+44" },
  { name: "United States", code: "+1" },
  { name: "Uruguay", code: "+598" },
  { name: "Uzbekistan", code: "+998" },
  { name: "Vanuatu", code: "+678" },
  { name: "Vatican City", code: "+379" },
  { name: "Venezuela", code: "+58" },
  { name: "Vietnam", code: "+84" },
  { name: "Wallis and Futuna", code: "+681" },
  { name: "Yemen", code: "+967" },
  { name: "Zambia", code: "+260" },
  { name: "Zimbabwe", code: "+263" }
];

export const CompanyTypeArray = [
   "Private Limited",
  "Public Limited",
  "Sole Proprietorship",
  "Partnership",
  "Government",
  "Non-Profit",
  "Startup",
  "MNC (Multinational Corporation)",
  "LLP (Limited Liability Partnership)",
  "Co-operative",
  "Franchise",
   "Manufacturing",
  "Engineering",
  "EPC",
  "General Construction Contractor",
  "Trading and Material Supply",
  "Transportation and Logistics",
  "IT",
  "Resources Supply (Manpower and Equipment)",
  "Heavy lifting and Hauling",
  "Scaffolding Services",
  "Shoring and Dewatering",
  "Land Survey",
  "Electrical Termination and Jointing",
  "Inspection and Testing Services",
  "Conveyor Installation",
  "HDPE Liner Installation",
  "FRP / GRP / RTR Contractor",
  "HDPE Piping",
  "Earth moving",
  "Project Consultancy",
  "Specialized Services (add as needed)",

]

export const CompanyLocationArray = [
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Mecca, Saudi Arabia",
  "Medina, Saudi Arabia",
  "Dammam, Saudi Arabia",
  "Khobar, Saudi Arabia",
  "Dhahran, Saudi Arabia",
  "Taif, Saudi Arabia",
  "Abha, Saudi Arabia",
  "Khamis Mushait, Saudi Arabia",
  "Al Hofuf, Saudi Arabia",
  "Al Mubarraz, Saudi Arabia",
  "Jubail, Saudi Arabia",
  "Hafar Al-Batin, Saudi Arabia",
  "Al Qatif, Saudi Arabia",
  "Najran, Saudi Arabia",
  "Yanbu, Saudi Arabia",
  "Al Khafji, Saudi Arabia",
  "Buraidah, Saudi Arabia",
  "Unaizah, Saudi Arabia",
  "Hail, Saudi Arabia",
  "Arar, Saudi Arabia",
  "Sakaka, Saudi Arabia",
  "Jizan, Saudi Arabia",
  "Tabuk, Saudi Arabia",
  "Al Bahah, Saudi Arabia",
  "Al Wajh, Saudi Arabia",
  "Ras Tanura, Saudi Arabia",
  "Al Majma'ah, Saudi Arabia",
  "Al Qurayyat, Saudi Arabia",
  "Al Lith, Saudi Arabia",
  "Al Aflaj, Saudi Arabia",
  "Al Kharj, Saudi Arabia",
  "Rabigh, Saudi Arabia",
  "Turaif, Saudi Arabia",
  "Al Ula, Saudi Arabia",
  "Al Birk, Saudi Arabia",
  "Al Duwadimi, Saudi Arabia",
  "Thuwal, Saudi Arabia",
  "Duba, Saudi Arabia",
  "Wadi ad-Dawasir, Saudi Arabia",
  "Baljurashi, Saudi Arabia",
  "Al Muzahimiyah, Saudi Arabia",
  "Al Namas, Saudi Arabia",
  "Bisha, Saudi Arabia",
  "Mahd adh Dhahab, Saudi Arabia",
  "Umluj, Saudi Arabia",
  "Al Bukayriyah, Saudi Arabia",
  "Samtah, Saudi Arabia",
  "Sabya, Saudi Arabia",
  "Ranyah, Saudi Arabia",
  "Qurayyat, Saudi Arabia",
  "Sharurah, Saudi Arabia",
  "Ad Dilam, Saudi Arabia",
  "Muzahmiyya, Saudi Arabia",
  "Afif, Saudi Arabia",
  "Al Zulfi, Saudi Arabia",
  "Al Artawiyah, Saudi Arabia",
  "Hotat Bani Tamim, Saudi Arabia",
  "Dawadmi, Saudi Arabia",
  "Al-'Uyayna, Saudi Arabia",
  "Qatif, Saudi Arabia",
  "Al Jumum, Saudi Arabia",
  "Al Awjam, Saudi Arabia",
  "Al Darb, Saudi Arabia",
  "Tanumah, Saudi Arabia",
  "Turubah, Saudi Arabia"
];

export const yearOptions = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90
];
export const skillOptions = [
  "JavaScript", "TypeScript", "React", "Angular", "Vue.js", "Node.js", "Express",
  "MongoDB", "PostgreSQL", "MySQL", "Python", "Django", "Flask", "Java", "Spring Boot",
  "C#", ".NET", "PHP", "Laravel", "Ruby", "Rails", "Go", "Flutter", "Swift", "Kotlin",
  "AWS", "Azure", "Google Cloud", "Docker", "Kubernetes", "Git", "CI/CD", "REST API",
  "GraphQL", "HTML", "CSS", "Tailwind", "Bootstrap", "Figma", "UI/UX", "Linux", "Bash",
  "Next.js", "NestJS", "Redis", "RabbitMQ", "Microservices", "Serverless", "Selenium",
  "Jest", "Cypress", "Webpack", "Vite", "Prisma", "TypeORM", "MongoDB", "Firebase"
];
// src/Constants/FormOptions.js
  export const COUNTRY_CITY_MAP = {
  India: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Chennai",
    "Kolkata",
    "Hyderabad",
    "Pune",
    "Ahmedabad",
    "Surat",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Navi Mumbai",
    "Prayagraj",
    "Ranchi",
    "Howrah",
    "Coimbatore",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Guwahati",
    "Chandigarh",
    "Solapur",
    "Mysore",
    "Tiruchirappalli",
    "Bareilly",
    "Aligarh",
    "Hubli-Dharwad",
    "Moradabad",
    "Gurugram",
    "Jalandhar",
    "Tiruppur",
    "Bhubaneswar",
    "Salem",
    "Mira-Bhayandar",
    "Warangal",
    "Guntur",
    "Bhiwandi",
    "Saharanpur",
    "Kochi",
    "Thiruvananthapuram",
    "Amravati",
    "Noida",
    "Jamshedpur",
    "Bhilai",
    "Cuttack",
    "Firozabad",
    "Bhavnagar",
    "Dehradun",
    "Durgapur",
    "Asansol",
    "Nanded",
    "Kolhapur",
    "Ajmer",
    "Kalaburagi",
    "Jamnagar",
    "Ujjain",
    "Loni",
    "Siliguri",
    "Malegaon",
    "Udaipur",
    "Jhansi",
    "Beawar",
    "Sangli",
    "Bharatpur",
    "Panihati",
    "Bidhannagar",
    "Pallavaram",
    "Nagercoil",
    "Aizawl",
    "Agartala",
    "Itanagar",
    "Pondicherry",
    "Imphal",
    "Shillong",
    "Dimapur",
    "Kohima",
    "Margao",
    "Daman",
    "Port Blair"
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca (Makkah)",
    "Medina (Al Madinah)",
    "Dammam",
    "Al Khobar",
    "Dhahran",
    "Ta'if",
    "Tabuk",
    "Abha",
    "Khamis Mushait",
    "Hail",
    "Buraidah",
    "Jubail",
    "Yanbu",
    "Qatif",
    "Al Qunfudhah",
    "Najran",
    "Sakakah",
    "Ḩaʼil",
    "Ar Rass",
    "Afif",
    "Al Bahah",
    "Bisha",
    "Al-Jawf",
    "Al Kharj",
    "Az Zulfi",
    "Al Majma'ah",
    "Rabigh",
    "Al Lith",
    "Al Qatif",
    "Dawadmi",
    "Al Wajh",
    "Mahayel",
    "Baljurashi",
    "Al Hareeq",
    "Shaqra",
    "Al Bukayriyah",
    "Unaizah",
    "Al Mithnab",
    "Hotat Bani Tamim",
    "Al Duwadimi",
    "Al Zulfi",
    "Ranyah",
    "Al Namas",
    "Al Aflaj",
    "Al Ghat",
    "Turaif",
    "Al Qurayyat",
    "Al Sajir",
    "Al Muzahimiyah",
    "Al Nafud",
    "Badr",
    "Al Khafji",
    "Ras Al Khair",
    "King Abdullah Economic City (KAEC)"
  ],
  Other: [
    "Not Applicable"
  ],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  UK: ["London", "Birmingham", "Manchester", "Liverpool", "Glasgow"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  Germany: ["Berlin", "Munich", "Frankfurt", "Hamburg"],
  UAE: ["Dubai", "Abu Dhabi", "Sharjah"],
  Singapore: ["Singapore"],
  // Add more as needed
};